---
global:
  nameOverride: &app_name scroll-proving-sdk
  fullnameOverride: *app_name

image:
  repository: scrolltech/sdk-cloud-prover
  pullPolicy: Always
  tag: sindri-2791edca

command:
  - "/bin/sh"
  - "-c"
  - "exec cloud --config /sdk_prover/config.json"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: true
    type: configMap
    mountPath: /sdk_prover/
    name: scroll-proving-sdk-config

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

scrollConfig: |
  {}
