---
global:
  nameOverride: &app_name scroll-proving-sdk
  fullnameOverride: *app_name

image:
  repository: scrolltech/sdk-cloud-prover
  pullPolicy: Always
  tag: sindri-v0.0.1

command:
  - "/bin/sh"
  - "-c"
  - "exec cloud --config /sdk_prover/config.json"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  config:
    enabled: true
    type: configMap
    mountPath: /sdk_prover/
    name: scroll-proving-sdk-config  # Change this value to <ReleaseName>-config
  keys:
    enabled: true
    type: pvc
    mountPath: /keys/
    size: 10Mi
    accessMode: ReadWriteOnce

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

# scrollConfig should be overwritten the config in json format. See the example below.
scrollConfig: |
  {}
#  {
#   "prover_name_prefix": "sindri_",
#   "keys_dir": "keys",
#   "coordinator": {
#     "base_url": "https://coordinator-api.scrollsdk",
#     "retry_count": 3,
#     "retry_wait_time_sec": 5,
#     "connection_timeout_sec": 60
#   },
#   "l2geth": {
#     "endpoint": "https://l2-rpc.scrollsdk"
#   },
#   "prover": {
#     "circuit_type": 3,
#     "circuit_version": "v0.13.1",
#     "n_workers": 1,
#     "cloud": {
#       "base_url": "https://sindri.app/api/v1/",
#       "api_key": <API_KEY>,
#       "retry_count": 3,
#       "retry_wait_time_sec": 5,
#       "connection_timeout_sec": 60
#     }
#   }
#  }
