name: Rust

on:
  push:
    branches: [ "feat-test-ci" ]
  pull_request:
    branches: [ "feat-test-ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev liblz4-dev libzstd-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
